### ISSUE TITLE
Pinguino v13 Installation - Installer v1.8.0.0

### ISSUE THREAD

**Issue by mathestro** [PinguinoIDE/pinguino-installers#14]
Dear Friends,

Few days ago I started with the basic examples for Pinguino OTG Olimex board. SD examples didn't work, DumpFile script uses the function "SD.mount" using one only argument, but library fileio.c uses two arguments; module and cs pin. I didn't see any reference to module argument, so, I assumed that is an argument to create an object and use multiple SD modules (in which second's argument will change, CS pin).

Due to this many problems, I decided to install latest version of Pinguino. I made some changes to the "NIS" file, some keys like HKLM to HKCU to fit the Windows registry and python's download file name (changing "." for "-" and "msi" to "exe", according to the available files on FTP; if not, then an error takes place).

Now Pinguino IDE is full installed, but still get some errors, like this, when I try to open "DumpFile" example:

Traceback (most recent call last):
  File "C:\Program Files\Pinguino\v13\pinguino-ide\pinguino\qtgui\ide\methods\decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v13\pinguino-ide\pinguino\qtgui\ide\methods\core.py", line 1067, in ide_open_file_from_path
    editor.text_edit.setPlainText(content)
AttributeError: 'NoneType' object has no attribute 'text_edit'

Almost all function of IDE are throwing this bug window.

Resume...

Where I post the SD.mount questions? Pinguino.cc is down. Can I use pinguino bootloader with MPLAB IDE meanwhile Pinguino IDE v13 is fixed?

**Comment by mathestro** [comment]
This is the first bug window at startup.

Traceback (most recent call last):
  File "C:\Program Files\Pinguino\v13\pinguino-ide\pinguino\qtgui\ide\methods\decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "C:\Program Files\Pinguino\v13\pinguino-ide\pinguino\qtgui\ide\ide.py", line 132, in __init__
    self.PinguinoAutoCompleter = PinguinoAutoCompleter()
  File "C:\Program Files\Pinguino\v13\pinguino-ide\pinguino\qtgui\ide\custom_widgets\code_editor\autocompleter.py", line 59, in __init__
    with open(os.path.join(os.getenv("PINGUINO_USER_PATH"), "reserved.pickle"), "rb") as file_reserved:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Psico\\Documents\\Pinguino\\v13\\reserved.pickle'

**Comment by MefhigosetH** [comment]
Dear @mathestro ,

Sory for the delay. Please, check this comment:

https://github.com/PinguinoIDE/pinguino-ide/issues/118#issuecomment-633256747
