### ISSUE TITLE
Linux Installer_v2

### ISSUE THREAD

**Issue by luzemario** [PinguinoIDE/pinguino-installers#18]
Hi,

After installing Pinguino 13 over an failed installation from old installer_1.2.2, it was successful. But after an clean install on Ubuntu 20.04 LTS, there are some weird messages because paths.conf are incorrect:

``` WARNING:root:Missing Pinguino libraries instalation. Make sure the paths in /home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/paths.conf are correct.
Traceback (most recent call last):
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/ide/child_windows/submit_bug.py", line 114, in submit_now
    self.save_for_later(summary, details, repo, environ, username, password)
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/ide/child_windows/submit_bug.py", line 177, in save_for_later
    parser.write(open(filename, "w"))
FileNotFoundError: [Errno 2] Arquivo ou diretório não encontrado: '/home/regis/Pinguino/v13/pinguino-user/submit-2020-11-13 17:11:58.602481'

```

Some one can tell me who is "regis"??? :-)

**Comment by luzemario** [comment]
More info from bug report window:

``` Traceback (most recent call last):
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/ide/methods/decorators.py", line 281, in wrapped
    return fn(Pinguino, *args, **kwargs)
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/ide/ide.py", line 57, in __init__
    PinguinoConfig.check_user_files()
  File "/home/luzemario/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/pinguino_core/pinguino_config.py", line 112, in check_user_files
    makedirs(os.getenv("PINGUINO_USER_PATH"), exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permissão negada: '/home/regis'
```
Still wondering who is "regis"... :-D

**Comment by luzemario** [comment]
Solved the issue myself. There was a ~/Pinguino folder with a previous install. I cannot guess who was regis at all... :+1:

**Comment by MefhigosetH** [comment]
Dear @luzemario ,

Thanks for your contact. Regis is the actual 'owner' of the Pinguino Project. His home dir is the default config in paths and other files. But generally this information is uptated autommatically by the installers (windows/Linux).

Can you, please, paste your `~/.pinguino/v13/pinguino-ide-fix-linux-support/pinguino/qtgui/config/pinguino.linux.conf` file, so I can help you ?

Do you use the new Linux installer published on Pinguino website ? Do you see errors while installing?

Best regards

**Comment by luzemario** [comment]
This bug was caused by using "Reset IDE configuration" function. It appears to erase some "possibly" bad conf files, but do not recreate them. It is funny to see Pinguino 13 attempting to check @rblanchot folders by default... :-D

The lack of paths.conf makes Pinguino 13 search for the config files on Regis' folders.

**Comment by luzemario** [comment]
To solve the issue, one can do the following:

1. Make a backup of user .pde files inside ~/Pinguino;
2. Enter `rm -rf ~/Pinguino ~/.pinguino`, from terminal;
3. Do a full reinstall;
3. Restore your .pde files to ~/Pinguino.
